VANNA_MODEL = "artman-jr"
VANNA_API_KEY = "07d5f470733f4d34ba47420daf195b10"
DB_HOST = "db.ldfzfxhwxzxwirvfpbul.supabase.co"
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASSWORD = "CUbm5JmY5rtw_MN"  
DB_PORT = 5432

password = "H2XqF.vNsEfD55_j29fdsq@*d"